### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by Yuri-NagaSaki**

### CODE REVIEW

**Comment by stephanlamoureux** [comment]
Hi @Sayyiku, this is really cool! Thanks for taking the time to translate my guide. Could you just make 2 small changes for me?

1. Add the footnotes back to the header on line 71, it should look like:  WSL [^1] [^2] [^3]
2. The English link doesn't work up top on the Chinese version on line 7

Those are the only issues I see. I will be adding more content to this soon as well, keep an eye out if you would like to continue translating :) Thanks again!

**Review by stephanlamoureux — CHANGES_REQUESTED** [review]
Hi @Sayyiku, this is really cool! Thanks for taking the time to translate my guide. Could you just make 2 small changes for me?

1. Add the footnotes back to the header on line 71, it should look like:  WSL [^1] [^2] [^3]
2. The English link doesn't work up top on the Chinese version on line 7

Those are the only issues I see. I will be adding more content to this soon as well, keep an eye out if you would like to continue translating 😎 Thanks again!

**Comment by Yuri-NagaSaki** [comment]
Thank you for the offer, I have completed both changes.

**Review by stephanlamoureux — APPROVED** [review]

**Comment by stephanlamoureux** [comment]
This was unexpected and really cool of you, I appreciate it very much!

**Pull request merged**
